FROM --platform=linux/arm64 node:20-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY prisma/schema.prisma ./

RUN yarn add prisma

EXPOSE 5555

CMD [ "yarn", "prisma", "studio" ]